# Generated by Django 5.1.7 on 2025-03-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
